# GitHub Actions workflow: Build and publish a Docker image to GHCR on push to main
name: Build and Publish Docker Image

on:
  push:
    branches: [ main ] # Trigger when commits land on main
  pull_request:
    branches: [ main ] # Validate PRs targeting main
  workflow_dispatch: # Allow manual runs from the Actions tab

# Least-privilege permissions required for this workflow
permissions:
  contents: read # read repo contents (needed for checkout)
  packages: write # push images to GitHub Container Registry
  id-token: write # enable provenance/SLSA attestation by build-push-action

# Reusable values available to all jobs/steps
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # e.g. owner/repo (may be mixed-case)

jobs:
  build-and-push:
    name: Build and push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Quality gates: install and run pnpm tasks before any Docker build ---
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          run_install: false

      - name: Install dependencies
        shell: bash
        run: |
          echo "::group::pnpm install"
          pnpm --version
          pnpm install --frozen-lockfile
          echo "::endgroup::"

      - name: Run format
        shell: bash
        run: |
          echo "::group::pnpm format"
          pnpm format
          echo "::endgroup::"

      - name: Run lint
        shell: bash
        run: |
          echo "::group::pnpm lint"
          pnpm lint
          echo "::endgroup::"

      - name: Run type check
        shell: bash
        run: |
          echo "::group::pnpm check"
          pnpm check
          echo "::endgroup::"

      - name: Generate licenses
        shell: bash
        run: |
          echo "::group::pnpm gen:licenses"
          pnpm run gen:licenses
          echo "::endgroup::"

      - name: Build app
        shell: bash
        run: |
          echo "::group::pnpm build"
          pnpm build
          echo "::endgroup::"

      - name: Set up QEMU (for multi-arch builds)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # auto-provided token with package:write

      - name: Extract version from package.json
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: version
        shell: bash
        run: |
          echo "::group::Read version from package.json"
          # Read the semver (x.y.z) from package.json and split into parts
          VERSION=$(jq -r .version package.json)
          echo "Detected version: ${VERSION}"
          if [[ -z "$VERSION" || "$VERSION" == "null" ]]; then
            echo "Could not read version from package.json" >&2
            echo "::endgroup::"
            exit 1
          fi
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          echo "Parsed parts => MAJOR=${MAJOR}, MINOR=${MINOR}, PATCH=${PATCH}"
          echo "::endgroup::"
          # Expose outputs for downstream steps
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "major=$MAJOR" >> $GITHUB_OUTPUT
          echo "minor=$MINOR" >> $GITHUB_OUTPUT
          echo "patch=$PATCH" >> $GITHUB_OUTPUT

      - name: Compute tags
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: meta
        shell: bash
        run: |
          echo "::group::Compute image reference and tags"
          # Compose the full image reference and tag set
          # Lowercase the owner/repo to satisfy Docker/OCI naming rules
          IMAGE_NAME_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_REF=${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}
          MAJOR=${{ steps.version.outputs.major }}
          MINOR=${{ steps.version.outputs.minor }}
          PATCH=${{ steps.version.outputs.patch }}
          VERSION=${{ steps.version.outputs.version }}

          echo "Original IMAGE_NAME: ${{ env.IMAGE_NAME }}"
          echo "Normalized (lowercase) IMAGE_NAME: ${IMAGE_NAME_LOWER}"
          echo "Image reference: ${IMAGE_REF}"
          echo "Using version parts => MAJOR=${MAJOR}, MINOR=${MINOR}, PATCH=${PATCH}"

          TAGS=(
            "${IMAGE_REF}:latest"          # always update latest
            "${IMAGE_REF}:${MAJOR}"        # major tag, e.g. 1
            "${IMAGE_REF}:${MAJOR}.${MINOR}"  # minor tag, e.g. 1.2
            "${IMAGE_REF}:${VERSION}"      # full semver, e.g. 1.2.3
          )

          echo "Planned tags:"
          for t in "${TAGS[@]}"; do echo " - ${t}"; done

          # Join tags with comma for build-push-action
          TAGS_CSV=$(IFS=, ; echo "${TAGS[*]}")
          echo "tags=$TAGS_CSV" >> $GITHUB_OUTPUT
          # Also expose normalized values for later steps
          echo "image_name_lower=${IMAGE_NAME_LOWER}" >> $GITHUB_OUTPUT
          echo "image_ref=${IMAGE_REF}" >> $GITHUB_OUTPUT
          echo "Computed tags CSV: ${TAGS_CSV}"
          echo "::endgroup::"

      - name: Build (and push on main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          provenance: true # generate provenance (SLSA) metadata
          sbom: true # generate SBOM and attach to the image
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
          # Enable build cache stored in GHCR for faster rebuilds
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ steps.meta.outputs.image_name_lower }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ steps.meta.outputs.image_name_lower }}:buildcache,mode=max

      - name: Summarize publish details
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        shell: bash
        run: |
          echo "## Docker Image Build Summary" >> "$GITHUB_STEP_SUMMARY"
          echo "Repository: ${{ env.REGISTRY }}/${{ steps.meta.outputs.image_name_lower }}" >> "$GITHUB_STEP_SUMMARY"
          echo "Version: ${{ steps.version.outputs.version }}" >> "$GITHUB_STEP_SUMMARY"
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Action: Pushed the following tags:" >> "$GITHUB_STEP_SUMMARY"
            IFS=',' read -ra TAGS_ARR <<< "${{ steps.meta.outputs.tags }}"
            for t in "${TAGS_ARR[@]}"; do echo "- $t" >> "$GITHUB_STEP_SUMMARY"; done
          else
            echo "Action: Build completed without publishing (pull_request or non-main)." >> "$GITHUB_STEP_SUMMARY"
          fi
